version: "2"

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - ineffassign
    - nilerr
    - nilnil
    - nilnesserr
    - errorlint
    - wrapcheck
    - exhaustive
    - revive
    - gocritic
    - predeclared
    - cyclop
    - funlen
    - nestif
    - gosec
    - bodyclose
    - sqlclosecheck
    - rowserrcheck
    - nolintlint
    - misspell

issues:
  exclude-use-default: false

formatters:
  enable:
    - gofmt
    - goimports
